config/routes.rb
Rails.application.routes.draw do

  root to: 'home_page#index'
  get 'home_page/index'

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  devise_scope :user do
    get     '/signin',          to: 'devise/sessions#new',          as: 'new_user_session'
    post    '/signin',          to: 'devise/sessions#create',       as: 'user_session'

    delete  '/signout',         to: 'devise/sessions#destroy',      as: 'destroy_user_session'
    
    get     '/signup',          to: 'devise/registrations#new',     as: 'new_user_registration'
    post    '/signup',          to: 'devise/registrations#create',  as: 'user_registration'   
    put     '/signup',          to: 'devise/registrations#update',  as: 'registration_path'
    delete  '/signup',          to: 'devise/registrations#destroy', as: 'destroy_user'
    get     '/edit-user',       to: 'devise/registrations#edit',    as: 'edit_user_registration'
    
    get     '/forgot-password', to: 'devise/passwords#new',         as: 'new_user_password'
    post    '/forgot-password', to: 'devise/passwords#create',      as: 'user_password'
    get     '/edit-password',   to: 'devise/passwords#edit',        as: 'edit_user_password'
    put     '/forgot-password', to: 'devise/passwords#update',      as: 'password_path'
  end


  resources :laptops do
    get 'edit', on: :member
    get '/send-detail',   to: 'laptops#send_detail'
  end
  
  get '/select-brand',  to: 'laptops#select_brand'
  get '/auto_search',   to: 'laptops#auto_search'

  resources :categories do
    get :index, on: :collection
  end
  resources :payments
  resources :orders
  resources :customers
  get '/references',   to: 'customers#references'
  resources :brands
  resources :shops

  get 'terms-condition', to: 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
	paginates_per 2
  validates   :name, :address, presence: true

  has_one_attached :image

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  has_many    :laptop_shops
  has_many    :laptops, through: :laptop_shops, dependent: :destroy

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all.page(params[:page])
    @info_window = Shop.all.map { |shop| [shop.name, shop.address, url_for(shop.image)] }
    @position = Shop.all.map{ |latlong| [latlong.latitude, latlong.longitude] }
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find_by_id(params[:id])
      redirect_to shops_path, notice: "Shop not found" if @shop.blank?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :address, :latitude, :longitude, :image)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.haml
.container
  .row
    .col-sm-9.col-md-7.col-lg-5.mx-auto
      .card.card-signin.my-5
        .card-body
          = form_with(model: shop, local: true) do |form|
            - if shop.errors.any?
              %h3
                = pluralize(shop.errors.count, "error")
                prohibited this shop from being saved:
              %ul
                - shop.errors.full_messages.each do |message|
                  %li= message
            = form.label :name
            = form.text_field :name, autofocus: true,       class: "form-control"
            = form.label :address
            = form.text_field :address, autofocus: true,    class: "form-control"
            = form.label :latitude
            = form.text_field :latitude, autofocus: true,   class: "form-control"
            = form.label :longitude
            = form.text_field :longitude, autofocus: true,  class: "form-control"
            = form.label          :image
            = form.file_field     :image, class: "form-control"
            .hr.my-4
            = form.submit "Submit", class: "btn btn-primary btn-block text-uppercase"

app/views/shops/edit.html.haml
.shop_view
  %h1.card-title.text-center Edit Shop
  = render 'form', shop: @shop
  %hr.my-4
  %div{:align => "center"}
    = link_to 'Show', @shop, 			class: "btn btn-primary"
    = link_to 'Back', shops_path, 	class: "btn btn-primary"

app/views/shops/index.html.haml
.laptop_view
  .container
    %h1 Shops
    %ul.nav.nav-tabs
      %li.nav-item
        %a.nav-link.active{"data-toggle" => "tab", :href => "#list"} List View
      %li.nav-item
        %a.nav-link{"data-toggle" => "tab", :href => "#map_wrapper"} Map View
    .tab-content
      #list.tab-pane.active
        %div{align: "right"}
          = link_to 'Add Shop', new_shop_path, class: "btn btn-primary"
        %table.table.table-hover.table-responsive
          %thead
            %tr
              %th Name
              %th Address
              %th Latitude
              %th Longitude
              %th
              %th
              %th

          %tbody
            - @shops.each do |shop|
              %tr
                %td= shop.name
                %td= shop.address
                %td= shop.latitude
                %td= shop.longitude
                %td= link_to 'Show', shop
                %td= link_to 'Edit', edit_shop_path(shop)
                %td= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' }
        %hr
        %div.d-flex.justify-content-center
          = paginate @shops

      #map_wrapper.container.tab-pane.fade
        #map_canvas.mapping
          :javascript
            function initialize() {
              var map;
              var bounds = new google.maps.LatLngBounds();
              map = new google.maps.Map(document.getElementById("map_canvas"));
              var markers = []
              markers = #{@position}
              var infoWindowContent = []
              var array = []
              infoWindowContent = #{raw @info_window}
              
              var infoWindow = new google.maps.InfoWindow(), marker, i;
              for( i = 0; i < markers.length; i++ ) {
                array[i] =  '<img src = '+ infoWindowContent[i][2] +' height = "150" width = "150" >' +
                            '<h5>' + infoWindowContent[i][0] + '</h5>' +
                            '<p>' + infoWindowContent[i][1] + '</p>'
                var position = new google.maps.LatLng(markers[i][0], markers[i][1]);
                bounds.extend(position);
                icon = {
                        url: "assets/marker.png",
                        scaledSize: new google.maps.Size(30, 30)
                }
                marker = new google.maps.Marker({
                  position: position,
                  map: map,
                  icon: icon
                });

                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                  return function() {
                    infoWindow.setContent(array[i]);
                    infoWindow.open(map, marker);
                  }
                })(marker, i));
              }
              map.fitBounds(bounds);
              var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
                this.setZoom(12);
                google.maps.event.removeListener(boundsListener);
              });
            }

  %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyBme_rTSaBqyrI_w_kAnpKe3j1O7bImt7Q&callback=initialize"}

app/views/shops/new.html.haml
.shop_view
  %h1.card-title.text-center Add Shop
  = render 'form', shop: @shop
  %hr.my-4/
  %div{:align => "center"}
    = link_to 'Back', shops_path, class: "btn btn-primary"

app/views/shops/show.html.haml
.shop_view
  .container
    .card-body
      %p#notice= notice
      %p
        %strong Name:
        = @shop.name
      %p
        %strong Address:
        = @shop.address
      %p
        %strong Latitude:
        = @shop.latitude
      %p
        %strong Longitude:
        = @shop.longitude

      = image_tag @shop.image.variant(resize: "400x400")

    %hr.my-4
    %div{:align => "center"}
      = link_to 'Edit', edit_shop_path(@shop),   class: "btn btn-primary"
      = link_to 'Back', shops_path,              class: "btn btn-primary"