config/routes.rb
Rails.application.routes.draw do

  root to: 'home_page#index'
  get 'home_page/index'

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  devise_scope :user do
    get     '/signin',          to: 'devise/sessions#new',          as: 'new_user_session'
    post    '/signin',          to: 'devise/sessions#create',       as: 'user_session'

    delete  '/signout',         to: 'devise/sessions#destroy',      as: 'destroy_user_session'
    
    get     '/signup',          to: 'devise/registrations#new',     as: 'new_user_registration'
    post    '/signup',          to: 'devise/registrations#create',  as: 'user_registration'   
    put     '/signup',          to: 'devise/registrations#update',  as: 'registration_path'
    delete  '/signup',          to: 'devise/registrations#destroy', as: 'destroy_user'
    get     '/edit-user',       to: 'devise/registrations#edit',    as: 'edit_user_registration'
    
    get     '/forgot-password', to: 'devise/passwords#new',         as: 'new_user_password'
    post    '/forgot-password', to: 'devise/passwords#create',      as: 'user_password'
    get     '/edit-password',   to: 'devise/passwords#edit',        as: 'edit_user_password'
    put     '/forgot-password', to: 'devise/passwords#update',      as: 'password_path'
  end


  resources :laptops do
    get 'edit', on: :member
    get '/send-detail',   to: 'laptops#send_detail'
  end
  
  get '/select-brand',  to: 'laptops#select_brand'
  get '/auto_search',   to: 'laptops#auto_search'

  resources :categories do
    get :index, on: :collection
  end
  resources :payments
  resources :orders
  resources :customers
  get '/references',   to: 'customers#references'
  resources :brands
  resources :shops

  get 'terms-condition', to: 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/laptop.rb
class Laptop < ApplicationRecord
  paginates_per 5

  has_many    :laptop_categories
  has_many    :categories, through: :laptop_categories, dependent: :destroy

  has_many    :laptop_shops
  has_many    :shops, through: :laptop_shops, dependent: :destroy

  belongs_to  :brand

  has_many_attached :images

  accepts_nested_attributes_for :laptop_categories, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :laptop_shops,      allow_destroy: true, reject_if: :all_blank
  
  validates   :model_number, :name, :ram, :hdd, :processor, :weight, :screen, :usb_port, :graphics_card, :hdmi_port,  presence: true
  validates   :serial_number, presence: true, uniqueness: true

  def self.search(laptop_id, brand_id, search_processor, search_screen, search_graphics_card)
    if laptop_id or brand_id or search_processor or search_screen or search_graphics_card
      where('id LIKE ? and brand_id LIKE ? and processor LIKE ? and screen LIKE ? and graphics_card LIKE ?', "%#{laptop_id}%", "%#{brand_id}%", "%#{search_processor}%", "%#{search_screen}%", "%#{search_graphics_card}%").order(:name)
    else
      order(:name)
    end
  end
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: [:show, :edit, :update, :destroy]
  # GET /laptops
  # GET /laptops.json
  def index
    @brands = Brand.all
    @brand_name   = params[:brand_id]
    @laptop_name  = params[:laptop_id]
    @laptops = Laptop.search(params[:brand_id], params[:laptop_id], params[:search_processor], params[:search_screen], params[:search_graphics_card]).page(params[:page])
  end

  def send_detail
    if params[:email]
      SendDetailJob.perform_later
    end
  end

  def auto_search
    auto_search = Laptop.where("processor LIKE ?", "%#{params[:term]}%").pluck(:processor).uniq
    render json: auto_search, status: :ok
  end

  def select_brand
    @brand = Brand.find_by_id(params[:brand_id])
    data = Laptop.where(brand_id: @brand.id).uniq
    render json: data
  end

  # GET /laptops/1
  # GET /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops
  # POST /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)
    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: 'Laptop was successfully created.' }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1
  # PATCH/PUT /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: 'Laptop was successfully updated.' }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: 'Laptop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find_by_id(params[:id])
      redirect_to laptops_path, notice: "Laptop not found" if @laptop.blank?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laptop_params
      params.require(:laptop).permit(:model_number, :name, :serial_number, :ram, 
                                    :hdd, :processor, :weight, :screen, 
                                    :graphics_card, :usb_port, :hdmi_port,
                                    :available, :brand_id, images: [],
                                    laptop_categories_attributes: [:id ,:laptop_id, :category_id, :_destroy ],
                                    laptop_shops_attributes: [:id ,:laptop_id, :shop_id, :latitude, :longitude, :_destroy ] )
    end

end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.haml
.container
  .row
    .col-sm-9.col-md-7.col-lg-5.mx-auto
      .card.card-signin.my-5
        .card-body
          = form_with(model: laptop, local: true) do |form|
            - if laptop.errors.any?
              %h3
                = pluralize(laptop.errors.count, "error")
                prohibited this laptop from being saved:
              %ul
                - laptop.errors.full_messages.each do |message|
                  %li= message
            = form.label          :model_number
            = form.text_field     :model_number, autofocus: true,   class: "form-control"
            = form.label          :name
            = form.text_field     :name, autofocus: true,           class: "form-control"
            = form.label          :brand
            = form.select("brand_id", Brand.all.collect {|brand| [ brand.name, brand.id ] },{include_blank: "Select Brand"}, class: "form-control")
            %br
            #categories
              = form.fields_for   :laptop_categories do |categories|
                = render 'laptop_category_fields', f: categories
              .links
                = link_to_add_association 'Add Category', form, :laptop_categories
            %br
            = form.label          :serial_number
            = form.text_field     :serial_number, autofocus: true,  class: "form-control"
            = form.label          :ram
            = form.text_field     :ram, autofocus: true,            class: "form-control"
            = form.label          :hdd
            = form.text_field     :hdd, autofocus: true,            class: "form-control"
            = form.label          :processor
            = form.text_field     :processor, autofocus: true,      class: "form-control"
            = form.label          :weight
            = form.text_field     :weight, autofocus: true,         class: "form-control"
            = form.label          :screen
            = form.text_field     :screen, autofocus: true,         class: "form-control"
            = form.label          :graphics_card
            = form.text_field     :graphics_card, autofocus: true,  class: "form-control"
            = form.label          :usb_port
            = form.number_field   :usb_port, autofocus: true,       class: "form-control"
            = form.label          :hdmi_port
            = form.number_field   :hdmi_port, autofocus: true,      class: "form-control"
            .custom-control.custom-checkbox.mb-3
              = form.check_box    :available,                class: "custom-control-input"
              = form.label        :available,                class: "custom-control-label"
            = form.label          :images
            = form.file_field     :images, multiple: true,   class: "form-control"
            %br
            #shops
              = form.fields_for   :laptop_shops do |shops|
                = render 'laptop_shop_fields', f: shops
              .links
                = link_to_add_association 'Add Shop', form, :laptop_shops
            %br
            %hr.my-4
            = form.submit "Submit", class: "btn btn-primary btn-block text-uppercase"

app/views/laptops/_laptop_category_fields.html.haml
.nested-fields
  = f.label :category
  = f.select("category_id", Category.all.collect { |category| [category.name, category.id] },{prompt: "Select Category"}, class: "form-control")
  = link_to_remove_association "Remove", f

app/views/laptops/_laptop_shop_fields.html.haml
.nested-fields
  = f.label :shop
  = f.select("shop_id", Shop.all.collect { |shop| [shop.name, shop.id] },{prompt: "Select Shop"}, class: "form-control")
  = link_to_remove_association "Remove", f

app/views/laptops/edit.html.haml
.laptop_view
  %h1.card-title.text-center Edit Laptop
  = render 'form', laptop: @laptop
  %hr.my-4
  %div{:align => "center"}
    = link_to 'Show', @laptop, 			class: "btn btn-primary"
    = link_to 'Back', laptops_path, class: "btn btn-primary"

app/views/laptops/index.html.haml
.laptop_view
  .container
    %h1 Laptops
    %div{align: "right"}
      = link_to 'Add Laptop', new_laptop_path, class: "btn btn-primary"
    = form_tag(laptops_path, method: :get, class: "form-inline") do
      = select_tag "brand_id", options_from_collection_for_select(@brands, "id", "name", @brand_name), {prompt: "Select Brand", class: "form-control dependent-dropdown", id: "brand_id", data: {url: "/select-brand?brand_id=", target: "laptop_id"} }
      = select_tag "laptop_id", options_from_collection_for_select(@laptops, "id", "name", @laptop_name), {prompt: "Select laptop" , class: "form-control", id: "laptop_id" }
      = text_field_tag :search_processor, params[:search_processor], placeholder: "Processor", class: "form-control autocomplete", autocomplete: "off", data: {url: "/auto_search"}
      = text_field_tag :search_screen, params[:search_screen], placeholder: "Screen", class: "form-control"
      = text_field_tag :search_graphics_card, params[:search_graphics_card], placeholder: "Graphics-card", class: "form-control"

      = submit_tag 'Search', class: "btn btn-primary"
    %table.table.table-hover.table-responsive
      %thead
        %tr
          %th Id
          %th Name
          %th Brand
          %th Category
          %th Ram
          %th Hdd
          %th Processor
          %th Screen
          %th Graphics card
          %th Available
          %th{:colspan => "3"} Action
          %th
      %tbody
        - @laptops.each do |laptop|
          %tr
            %td
              = laptop.id
            %td
              = laptop.name
            %td
              = laptop.brand.name
            %td
              - laptop.categories.each do |category|
                = category.name
            %td
              = laptop.ram
            %td
              = laptop.hdd
            %td
              = laptop.processor
            %td
              = laptop.screen
            %td
              = laptop.graphics_card
            %td
              = laptop.available
            %td
              = link_to 'Show', laptop
            %td
              = link_to 'Edit', edit_laptop_path(laptop)
            %td
              = link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' }
            %td
              = form_tag(laptop_send_detail_path(laptop_id: laptop.id), method: :get) do
                = text_field_tag :email, params[:email] ,placeholder: "Enter email", class: "form-control"
                = submit_tag 'Send detail'           
    %hr
    %div.d-flex.justify-content-center
      = paginate @laptops

app/views/laptops/new.html.haml
.laptop_view
  %h1.card-title.text-center Add Laptop
  = render 'form', laptop: @laptop
  %hr.my-4/
  %div{:align => "center"}
    = link_to 'Back', laptops_path, class: "btn btn-primary"

app/views/laptops/show.html.haml
.laptop_view
  .container
    .card-body
      #carouselExampleControls.carousel.slide{"data-ride" => "carousel"}
        .carousel-inner
          .carousel-item.active
            - @laptop.images.each do |image|
              = image_tag image.variant(resize: "200x200")

            %br
            %br
            %p
              %strong Model number:
              = @laptop.model_number
            %p
              %strong Name:
              = @laptop.name
            %p
              %strong Brand:
              = @laptop.brand.name
            %p
              %strong Category:
              - @laptop.categories.each do |category|
                = category.name
            %p
              %strong Serial number:
              = @laptop.serial_number
            %p
              %strong Ram:
              = @laptop.ram
            %p
              %strong Hdd:
              = @laptop.hdd
            %p
              %strong Processor:
              = @laptop.processor
            %p
              %strong Weight:
              = @laptop.weight
            %p
              %strong Screen:
              = @laptop.screen
            %p
              %strong Graphics card:
              = @laptop.graphics_card
            %p
              %strong Usb port:
              = @laptop.usb_port
            %p
              %strong Hdmi port:
              = @laptop.hdmi_port
            %p
              %strong Available:
              = @laptop.available
            %p
              %strong Shop:
              - @laptop.shops.each do |shop|
                = shop.name       
          %hr.my-4/
          %div{:align => "center"}
            = link_to 'Edit', edit_laptop_path(@laptop), class: "btn btn-primary"
            = link_to 'Back', laptops_path,              class: "btn btn-primary"