config/routes.rb
Rails.application.routes.draw do

  root to: 'home_page#index'
  get 'home_page/index'

  devise_for :users, skip: [:sessions, :registrations, :passwords]

  devise_scope :user do
    get     '/signin',          to: 'devise/sessions#new',          as: 'new_user_session'
    post    '/signin',          to: 'devise/sessions#create',       as: 'user_session'

    delete  '/signout',         to: 'devise/sessions#destroy',      as: 'destroy_user_session'
    
    get     '/signup',          to: 'devise/registrations#new',     as: 'new_user_registration'
    post    '/signup',          to: 'devise/registrations#create',  as: 'user_registration'   
    put     '/signup',          to: 'devise/registrations#update',  as: 'registration_path'
    delete  '/signup',          to: 'devise/registrations#destroy', as: 'destroy_user'
    get     '/edit-user',       to: 'devise/registrations#edit',    as: 'edit_user_registration'
    
    get     '/forgot-password', to: 'devise/passwords#new',         as: 'new_user_password'
    post    '/forgot-password', to: 'devise/passwords#create',      as: 'user_password'
    get     '/edit-password',   to: 'devise/passwords#edit',        as: 'edit_user_password'
    put     '/forgot-password', to: 'devise/passwords#update',      as: 'password_path'
  end


  resources :laptops do
    get 'edit', on: :member
    get '/send-detail',   to: 'laptops#send_detail'
  end
  
  get '/select-brand',  to: 'laptops#select_brand'
  get '/auto_search',   to: 'laptops#auto_search'

  resources :categories do
    get :index, on: :collection
  end
  resources :payments
  resources :orders
  resources :customers
  get '/references',   to: 'customers#references'
  resources :brands
  resources :shops

  get 'terms-condition', to: 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	paginates_per 2

  validates 	:name, 		presence: true, uniqueness: true
  validates 	:website, presence: true

  def self.search(search_brand_name)
 		if search_brand_name
 			where('name LIKE ?', "%#{search_brand_name}%").order(:name)
 		else
 			order(:name)
 		end
 	end
end

app/models/category.rb
class Category < ApplicationRecord
	paginates_per 2

	has_many		:laptop_categories
	has_many		:laptops, through: :laptop_categories, dependent: :destroy
    
	validates 	:name, presence: true, uniqueness: true

	def self.search(search_category_name)
 		if search_category_name
 			where('name LIKE ?', "%#{search_category_name}%").order(:name)
 		else
 			order(:name)
 		end
 	end
end

app/models/customer.rb
class Customer < ApplicationRecord
	paginates_per 2

	validates :name, :address,		presence: true
	validates :username, 					presence: true, uniqueness: true
	validates :number, 	format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }, length: { minimum: 10 }, uniqueness: true
	validates :email, 	format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true 

	def self.search(search_customer_name, search_customer_username)
 		if search_customer_name or search_customer_username 
 			where('name LIKE ? and username LIKE ?', "%#{search_customer_name}%", "%#{search_customer_username}%").order(:name)
 		else
 			order(:name)
 		end
 	end

end

app/models/laptop.rb
class Laptop < ApplicationRecord
  paginates_per 5

  has_many    :laptop_categories
  has_many    :categories, through: :laptop_categories, dependent: :destroy

  has_many    :laptop_shops
  has_many    :shops, through: :laptop_shops, dependent: :destroy

  belongs_to  :brand

  has_many_attached :images

  accepts_nested_attributes_for :laptop_categories, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :laptop_shops,      allow_destroy: true, reject_if: :all_blank
  
  validates   :model_number, :name, :ram, :hdd, :processor, :weight, :screen, :usb_port, :graphics_card, :hdmi_port,  presence: true
  validates   :serial_number, presence: true, uniqueness: true

  def self.search(laptop_id, brand_id, search_processor, search_screen, search_graphics_card)
    if laptop_id or brand_id or search_processor or search_screen or search_graphics_card
      where('id LIKE ? and brand_id LIKE ? and processor LIKE ? and screen LIKE ? and graphics_card LIKE ?', "%#{laptop_id}%", "%#{brand_id}%", "%#{search_processor}%", "%#{search_screen}%", "%#{search_graphics_card}%").order(:name)
    else
      order(:name)
    end
  end
end

app/models/laptop_category.rb
class LaptopCategory < ApplicationRecord
  belongs_to :laptop, 	optional: true
  belongs_to :category, optional: true

  validates_uniqueness_of	:laptop_id, scope: [:category_id]
end

app/models/laptop_shop.rb
class LaptopShop < ApplicationRecord
  belongs_to :laptop
  belongs_to :shop
end

app/models/order.rb
class Order < ApplicationRecord
	paginates_per 2
	
  belongs_to 	:laptop
  belongs_to 	:customer
  
  validates 	:shipping_address, :billing_address, :status, :amount, 	presence: true

  def self.search(laptop_id)
 		if laptop_id
 			where('laptop_id LIKE ?', "%#{laptop_id}%").order(:date)
 		else
 			order(:date)
 		end
 	end

end

app/models/payment.rb
class Payment < ApplicationRecord
	paginates_per 2
  belongs_to 	:order
  
  validates 	:mode, :status, :amount, presence: true

  def self.search(order_id)
 		if order_id
 			where('order_id LIKE ?', "%#{order_id}%").order(:mode)
 		else
 			order(:mode)
 		end
 	end
end

app/models/shop.rb
class Shop < ApplicationRecord
	paginates_per 2
  validates   :name, :address, presence: true

  has_one_attached :image

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  has_many    :laptop_shops
  has_many    :laptops, through: :laptop_shops, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LapStore
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      .container
        %a.navbar-brand{:href => "#"} LapStore
        %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            - if user_signed_in?
              %li
                = link_to 'Laptop',   laptops_path,    class: "nav-link"
              %li
                = link_to 'Customer', customers_path,  class: "nav-link"
              %li
                = link_to 'Order',    orders_path,     class: "nav-link"
              %li
                = link_to 'Brand',    brands_path,     class: "nav-link"
              %li
                = link_to 'Payment',  payments_path,   class: "nav-link"
              %li
                = link_to 'Category', categories_path, class: "nav-link"
              %li
                = link_to 'Shop',     shops_path,      class: "nav-link"
              %li
                = link_to 'Terms & Conditions',     terms_condition_path,      class: "nav-link"
              %li
                = link_to current_user.email, edit_user_registration_path,    class: "nav-link"
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete,class: "nav-link"
            - else
              %li
                = link_to 'Sign Up', new_user_registration_path, class: "nav-link js-scroll-trigger"
              %li
                = link_to 'Login', new_user_session_path,        class: "nav-link js-scroll-trigger"
  
  - if notice
    %p.alert.alert-success= notice
  - if alert
    %p.alert.alert-danger= alert

  = yield

  %footer.py-2.bg-dark
    .container
      %p.text-center.text-white Copyright © LapStore